import os

os.system('powershell "winget install --id Microsoft.WindowsTerminal -e"')
os.system('powershell "winget install Git.Git"')
os.system('powershell "winget install --id=Microsoft.PowerToys -e"')
os.system('powershell "winget install --id=GitHub.GitHubDesktop -e"')
os.system('powershell "winget install JanDeDobbeleer.OhMyPosh --source winget --scope user --force"')
os.system('powershell "mkdir $HOME/home"')
os.system('powershell "mkdir $HOME/home/workspace"')
os.system('powershell "git clone https://github.com/Ruunah/dotfiles $HOME/home/.config"')
os.system('powershell "git clone https://github.com/Ruunah/programs $HOME/home/.programs"')
os.system('powershell "mv $HOME/home/.config/term_windows/WindowsPowerShell $HOME/Documents"')
os.system('powershell "mv $HOME/home/.config/term_windows/settings.json $HOME/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"')
os.system('powershell "mv $HOME/home/.config/nvim $HOME/AppData/Local"')
os.system("""powershell 'git clone https://github.com/wbthomason/packer.nvim "$HOME/AppData/Local/nvim-data/site/pack/packer/start/packer.nvim"'""")
